In [2]:
import numpy as np
import random
import matplotlib.pyplot as plt;               
import plotly;                   
import plotly.graph_objs as go;
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot;
from IPython.display import display, HTML; init_notebook_mode(connected=True);
%matplotlib inline

In [3]:
a = np.array([5,8,-9,4,-7])

In [4]:
b = np.random.rand(10, 5)

In [5]:
def get_possibilites(p):
    # get dad gen randomly
    pai = np.random.randint(2, size = p)
    # the mom gen is given by
    mae = 1 - pai
    return pai, mae

In [6]:
def genetic_crossing(pai, mae):
    # create gen-cross possibilite
    p_pai, p_mae = get_possibilites(5)
    # select the dad gen
    gen_pai = np.multiply(pai, p_pai)
    # select the mom gen
    gen_mae = np.multiply(mae, p_mae)
    # new child is created
    child = gen_pai + gen_mae
    return child

In [7]:
genetic_crossing(b[4], b[5])

array([0.23217497, 0.40735379, 0.01964477, 0.16177064, 0.87891992])

In [8]:
def genetic_mutation(ind, n):
    for i in range(n):
        g = np.random.rand()
        ind[np.random.randint(5, size = 1)[0]] = g
    return ind

In [9]:
ind = genetic_crossing(b[4], b[5])

In [10]:
random.uniform(-0.1, 0.1)

-0.07281487364273392

In [11]:
def genetic_mutation_b(ind, n):
    for i in range(n):
        g = random.uniform(-0.2, 0.2)
        pos = np.random.randint(5, size = 1)[0]
        val = g + ind[pos]
        if val > 1:
            val = 1
        elif val < 0:
            val = 0

        ind[pos] = val
    return ind

In [12]:
genetic_mutation(ind, 1)

array([0.37581768, 0.40735379, 0.01964477, 0.85134663, 0.17770515])

In [13]:
def select_best_pop(a, b, qtd):
    # a = vetor ou função a ser otimizada
    # b = população de indivíduos 
    # qtd = quantidade de indivíduos a sobreviver
    
    v = np.dot(b, a) # maximizar o produto interno
    v = v/max(v)                     
    
    n_pop = len(b) # quantos indivíduos há na população
    
    aux = np.zeros((n_pop, 5 + 1)) # matriz auxiliar com n_pop linhas e l+1 colunas
    aux[:,:-1] = b # alimenta com os indivíduos
    aux[:,5:6] = np.array([v]).T  # alienta com seu rank individual
    b = aux[aux[:,5].argsort()[::-1]][0:qtd] # seleção e exclusão
    
    b = b[:,:-1] # pagamos apenas as colunas com os genes
    
    return b

In [14]:
select_best_pop(a, b, 3)

array([[0.80007189, 0.93403319, 0.46381411, 0.6049961 , 0.150037  ],
       [0.86778309, 0.94893894, 0.89205954, 0.97440743, 0.38812413],
       [0.23217497, 0.96598893, 0.38074104, 0.16177064, 0.17770515]])

In [15]:
def create_new_pop(b, n):
    n_pop = len(b)
    
    bnew = []
    pais = []
    maes = []
    for i in range(n):
        pai = 0; mae = 0
        while pai == mae:
            pai = np.random.randint(n_pop, size = 1)[0]
            mae = np.random.randint(n_pop, size = 1)[0]
            
        pais.append(pai)
        maes.append(mae)
        
        pai = b[pai]; mae = b[mae]
        
        ind = genetic_crossing(pai, mae)
        
        # creating an x-men by gen mutation for 10%
        if i%np.ceil(n/10) == 0:
            qtd_gen_x = np.random.randint(len(b[0]), size = 1)[0]
            ind = genetic_mutation(ind, qtd_gen_x)
            
        # creating an x-men by gen mutation (other-type) for 10%
        if i%np.ceil(n/11) == 0:
            qtd_gen_x = np.random.randint(len(b[0]), size = 1)[0]
            ind = genetic_mutation_b(ind, qtd_gen_x)
            
        bnew.append(list(ind))
        
    bnew = np.array(bnew)
    return bnew #, set(np.sort(pais)), set(np.sort(maes))

In [16]:
pop = create_new_pop(b, 100)

In [17]:
figure = {'data':[],'layout':{'title': 'Titulo'}}
for faz in range(10):
    VAR = np.random.rand(20, 5)
    #VAR = np.zeros((10, 5))
    #VAR = np.ones((10, 5))
    r = []; e = []; j = 0; v = 1
    prev = 10;  nextv = 1
    while j < 100:
        j = j+1
        VAR = create_new_pop(VAR, 100)
        VAR = select_best_pop(a, VAR, 10)
        
        prev = nextv
        nextv = sum(np.dot(VAR, a))
        
        v = np.abs(prev - nextv)
        
        r.append(v)
        e.append(j)
        
    figure['data'].append(go.Scatter(x = e,  y = r, name = 'teste'))

iplot(figure)

In [18]:
VAR

array([[1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.],
       [1., 1., 0., 1., 0.]])

In [19]:
np.dot(VAR[0], a)

17.0

In [20]:
np.dot([0,1,1,0,1], a)

-8

In [22]:
from IPython.display import clear_output
import time
for faz in range(1):
    VAR = np.random.rand(20, 5)
    #VAR = np.zeros((10, 5))
    #VAR = np.ones((10, 5))
    r = []; e = []; j = 0; v = 1
    prev = 10;  nextv = 1
    while j < 30:
        clear_output(wait = True)
        time.sleep(1.3) # seconds
        j = j+1
        VAR = create_new_pop(VAR, 100)
        VAR = select_best_pop(a, VAR, 10)
        
        prev = nextv
        nextv = sum(np.dot(VAR, a))
        
        v = np.abs(prev - nextv)
        
        r.append(v)
        e.append(j)
        print('Geração '+str(j))
        print(VAR[0])

Geração 30
[1. 1. 0. 1. 0.]
